# Generated by Django 3.2 on 2022-07-02 09:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0004_alter_todotask_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todotask',
            name='limit',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
