# Generated by Django 3.2 on 2022-07-04 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0010_alter_todotask_limit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todotask',
            options={'ordering': ('-start',)},
        ),
        migrations.AlterField(
            model_name='todotask',
            name='limit',
            field=models.DateField(null=True),
        ),
    ]
